spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ny_cab_data
    username: nycabuser
    password: NyCab@123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
  cache:
    jcache.config: classpath:ehcache.xml